mongodb:
  replicaCount: 1
  image:
    repository: mongo
    tag: latest
  service:
    type: ClusterIP
    port: 27017
  volumeMounts:
    - name: db-data
      mountPath: /data/db

mongoexp:
  replicaCount: 2
  image:
    repository: mongo-express
    tag: latest
  service:
    type: ClusterIP
    port: 8081
  volumeMounts:
    - name: my-custom-secret
      mountPath: /my-cusrt-file
  volumes:
    - name: my-custom-secret
      hostPath:
        path: /Users/thaovtran/my-cusrt-file

webapp:
  replicaCount: 2
  image:
    repository: thawtran/mandan-site
    tag: v0.3
  service:
    type: ClusterIP
    port: 8383
    targetPort: 3000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  mongodbHost: mandandb.k8s.local
  webappHost: mandanweb.k8s.local
  tls:
    enabled: true
    secretName: "k8s-local-secret-tls"

configmap:
  mongodb_url: ""

secrets:
  mongodb:
    username: dXNlcm5hbWU=
    password: cGFzc3dvcmQ=
  mongoexp:
    username: dXNlcm5hbWU=
    password: cGFzc3dvcmQ=
  tls:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZEVENDQXZXZ0F3SUJBZ0lVWWp2T2tIVmdndHlSTmI1djVwSXJOZ1B6Mnk0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZqRVVNQklHQTFVRUF3d0xLaTVyT0hNdWJHOWpZV3d3SGhjTk1qWXdNVEUwTVRBd01UVXpXaGNOTWpjdwpNVEUwTVRBd01UVXpXakFXTVJRd0VnWURWUVFEREFzcUxtczRjeTVzYjJOaGJEQ0NBaUl3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dJUEFEQ0NBZ29DZ2dJQkFMRitCUm5UVkE1OHcxYm1yS3lkT0F5czFHdTRRNnlYVzBDV1ZlRTUKVzNOKzJyb2xMc2FGNzVhQmw4cldmZGNmd1VuZTVHcWh6WnEzY3Z2NERtb0tva2RrblZSa203a3JqazF1NVBGeQpWM1phU0dybU9UVzgzUDRkdkk3WHZNUFBoOHJwNW5YUXFJZlJibU5TVE1IWENOY0VWMmo3RXdDV0NPT0p1RTNNClVzQXpRdzNrL0tXMDR1eFhPbVNTZXBCYm5iU1BqL2liSmdhNEczVXRuVUpRbE41NWZVOUk4V3pwdHd3ekFZc2wKQVZWa2lRa2RramJKMFJRTHFRazZDeXNwOG9wRk5ELzlEd3RwTkxJRmcxcFR4M3hDWWFvc3Q5TVhCRnZ0UjBFVApxam10SWVMaXBvOUpzRnRGYytqRjE2bnljQVlJNW1ENjdldnJ2ODRpMEZrRzBxdlRtZy9OWjd6Q2g2Q2IyMFJlCndKbTVBUnBNeitYZDV4Q3A4VEJab3RnYTJ6OVdTQXJzcm8wbUNzay9DWnFWZ1NQeWxEUDY5UHZuTzMvYzBEZGIKS255cndLamRwZWU5aTdnaXZpMXI2SHpLQUdiVi92SEZpZTNBYzJvdmdLaDJ1Y0t2S05DNUZld2NDaEw3S1Z0eQpCd3BtQk1YUk00Q2dRS00rQlhERHh5bUpVOUdtVzRObm0xMC8yblpQNFR2a1dVZWVMY3pzbnRSanZrMVpIYzl0CkllMDlUVmtwSTZaUmx5TThSemxkSmpOWHdjMGlvdksrdGRoamJFZGlic1NSK0FqWXhtcXY0NllNTytzUy9LU3gKdXRXWTZZR0k1eXU0dCtwNnlwdUI0a3JJdVhxdlBVS1o0cDFhdjBqNXV1WlJPNnNRVGtGbFFxSnhrMitwbzZLNAo2S0hkQWdNQkFBR2pVekJSTUIwR0ExVWREZ1FXQkJROEo3L2VJcG5ENHJWRG5ZTndJbEN0TzNLY2VUQWZCZ05WCkhTTUVHREFXZ0JROEo3L2VJcG5ENHJWRG5ZTndJbEN0TzNLY2VUQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEcKQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUJiVTIyVlJpczJwOXJWYTArQUQ2REg2ZENkYnVTTERjSHgzUjcrRGdVRgpubzdzN1Qxek1lN2lDTjdxcWJYYlhHa0xWRXR4VXU0alp3L1ZZdFRZWDdvcEVQVFZrZmVUMWtheExuc2xqckRaCkl1TGl6aE1TTDU0bjZ3YlM2RjlWckIvZDRsQUtqcnBhU3lLR1RUWTJxRnFhQzhKR0xQNjZGeVphRVNmZXhiTmQKelRpYTdpbTRibUNQdEh2ODN4L2laaHBJYTZKSnBTTDdONExPNnF5VU83dXpEOHJqbFJkVjNJRDBPclVjNEZBTQp4NXIzYmFpTncrT1hDNHpYU1RzZmhWdnp4NUtxdVd5TG1Qb25LZ3VDUGMxU3lpRmRYa2g4Y0d0MERtQVVkc2pnClhsblNGOFpacFFvRUZWanc5VlJZUDg3VlpJL0Vra0hmS1cvbVRaQzI0WDZlV3BjZFlhbURDU3N1U1REUUIvbFQKRmZGcFJqeWtWM2Y2WmwydFNuTGk4QUUrNWZva3VseG1Za25xODNjaTBhbFVmeGY0RmVhVkwrdW40OWNVdzFubwpiVENJbXJXVEV5dDFNR0VCcGp3OEFKQlRFbDBpZVVHOVJPTEJpeEUrOWVPNHdGMFB4QmtGaWVLL0tFSm1uZDlMCmRETlhRNUxoNC96bEtWdk9IQThuaWp6bjMraU5wdXlnamJ1ZEhBS3JqUkRzK1c2Qmd4WUdZVFZDcm9BUDVTVUcKdko2Y1pybkFXa1NiWUZGb05QWUJ5TGNEZGJUdGdHbk93Q0pWaDY2U0dITHBtZnBIOHZHMVdsWW9YbEpmOHUwdwpOdzNtVHREdFZ6T3AyUHR2d3UvRmhEa1dNOFVhWVpLd2MzdnFWT2ZZUHhwRTRUMVROcDVmVFk1RmtDc1pxOGJUCktnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpSQUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1M0d2dna3FBZ0VBQW9JQ0FRQ3hmZ1VaMDFRT2ZNTlcKNXF5c25UZ01yTlJydUVPc2wxdEFsbFhoT1Z0emZ0cTZKUzdHaGUrV2daZksxbjNYSDhGSjN1UnFvYzJhdDNMNworQTVxQ3FKSFpKMVVaSnU1SzQ1TmJ1VHhjbGQyV2tocTVqazF2TnorSGJ5TzE3ekR6NGZLNmVaMTBLaUgwVzVqClVrekIxd2pYQkZkbyt4TUFsZ2pqaWJoTnpGTEFNME1ONVB5bHRPTHNWenBra25xUVc1MjBqNC80bXlZR3VCdDEKTFoxQ1VKVGVlWDFQU1BGczZiY01Nd0dMSlFGVlpJa0pIWkkyeWRFVUM2a0pPZ3NyS2ZLS1JUUS8vUThMYVRTeQpCWU5hVThkOFFtR3FMTGZURndSYjdVZEJFNm81clNIaTRxYVBTYkJiUlhQb3hkZXA4bkFHQ09aZyt1M3I2Ny9PCkl0QlpCdEtyMDVvUHpXZTh3b2VnbTl0RVhzQ1p1UUVhVE0vbDNlY1FxZkV3V2FMWUd0cy9Wa2dLN0s2TkpnckoKUHdtYWxZRWo4cFF6K3ZUNzV6dC8zTkEzV3lwOHE4Q28zYVhudll1NElyNHRhK2g4eWdCbTFmN3h4WW50d0hOcQpMNENvZHJuQ3J5alF1UlhzSEFvUyt5bGJjZ2NLWmdURjBUT0FvRUNqUGdWd3c4Y3BpVlBScGx1RFo1dGRQOXAyClQrRTc1RmxIbmkzTTdKN1VZNzVOV1IzUGJTSHRQVTFaS1NPbVVaY2pQRWM1WFNZelY4SE5JcUx5dnJYWVkyeEgKWW03RWtmZ0kyTVpxcitPbUREdnJFdnlrc2JyVm1PbUJpT2NydUxmcWVzcWJnZUpLeUxsNnJ6MUNtZUtkV3I5SQorYnJtVVR1ckVFNUJaVUtpY1pOdnFhT2l1T2loM1FJREFRQUJBb0lDQUNnSEUwZnFkb21vM2RXK2dtRVFPTGgxCkRwZTNiNzJmeWJMRVpKdzlGdkJ5UW9vWndoVi8xWk1qNlROVGtZQWZGM1JkR2JhcGhFaDR5Q3ZtV252VUo1cEIKcU5DRU92RTB6eXdMendKYmhybDRiVjM4U3hraEhWYUtwc0F4QzQ4K1FYSERzNWRNeGdFUlBGdVdUeHlrN2NldAo0VGVaN2NSalVhQmM2ZTFUbjdMY0xLcFl3cGh0TllMV3ZpSzV2UDNLeDROVm9BS1JISytGdkIxK09ybWVtaUFkCkZtTTN3RWlQWVpwVTgydHBua1lmZk44TEpmTUlxd2ZpQkU1Q0lvd3FzdG0zZHl2YUdsYzRzK3RVM25WVHNRaUgKSU9iam5GWTAyZVVRV3hJa1NPNm1hcDZ6L2h1UTR2NkdhSGd0aS9BMTdra1NIMEJ1UHBOR3NKUWdta3VGaENOZQp2a0g0OGNqdTZXdXFDb1dDeUZjU0c0aHdmbXNLaktjUnF1MjR3K3Z5MUdudE9vNSt4OWNyWnNDcGpjdlVDdjlTCit5R1NDeWxaaXk2dEFSVlhUYXBpcjdTcFl0N0VPTXZMNDdrSEswTjdROWlWSTRPa01lNzhNT1hjVGhOdDlvbFAKSWxIV2tvOHI5akI2SmgwM3FJVUFvd3JHYVlDOFFxNG5IVXBTdGV0bTQ4WlVoM3d0RllLSlJkd0l0NGdqMzBMUgpZUmJHM1JWdSt3aGdzN3V3UW5uTllNK21DSHViM21TSnRwZGJBYTdieWlIVTljRldPS1ZYUUJyMFpzNHRnQVdTCm9mWUEzeVFObUt6NjRTUjkwZkdzdVBHN2RkWVdVVDQ3OFFsaWpNTkI4QUVKSC8vRncyeGF4UWlPVlVkM3lJdGwKT0JWWDdOTEhSZ1Y4RnUrbnlGd1JBb0lCQVFEdWRwVDBEalNOWURWUlZ2NnpKTzJpU1BtQ1Z0VEU1QUloRWZYTAozcE1ZWGh5TXhDZ3BJZzFBNzhWby93dWZxd0w4UXVMc2p4NVBNU3hnWHJlVWVOQk8xcXh6c3RQc2JsTUE3UUlaCjRmZTNXak4yK21WT2tOUEgvaDRyNjM5TXU1QTdqOXh3dEJZV1dIemZVRXVaV0ZjQ0piR2hlUm1EQjdXV1BLMzkKb2FWcHZZZm1BSGhuM2MwbTJ4RVczU1I1N2JtT2dabTBWeVpGOUdOWDBmNCtETHBvZG1DM3UrbVJFNlRXNFRMZgpmK0lFMXNaTkMvdmpqYkRnSDJiZjlJSU4zWUMrbytWUm4zOC94d0R5eHhrempVNmQzVGRQZFVNNDFRdnVORjEvCjdNaGxsOVR6dkNlVVUwNWRpelRudGRta0RxbUVlb0h1bW1EQ3RnelBlQnFJa243TkFvSUJBUUMraTVJdFNZTWoKU1J0c3RJS2VIemdWRURSYytOZmFOUHlndTFESUs2d1dRaityK3BVc1JrQTF5YitETDkyV1lRM2FhUE5Da0pLRwpoaC9IbW5QMSt2RXgzOFBRMytuVlgreTN0NHRTNjgzTWcrRzZtZElOYzhZM2o0UUVscC9yb2pXT3hyWmpWZDRJCmFDYVdCUnlMOFNWSUdLNXRKdmo2ZGVtcGdqYW40ZSt3cVF3WXE0RU1qZ2NVVDA0SmlKM3NidWx5M2dhS2lSWjIKRlVXREhGd0hkbWNsemdUMjVWZW01RHV0bURQOXkwaHpvaDIrZkg4Nm9XZVNjczFWMExIT2lwK0xHeXVRNjBIVwpRc0JxZUljRk44QkdqNmhSYW9DdDNpUEtmZVJUb2pVVGFVNEl0Qkh0ai8vVlJyRmRXeDNkMFRrckF3VW9vY1ptCk1aVlhURjB3b285UkFvSUJBUURUeFRtSTkraVJ1T1FBeFdwUis3U1J6NDdOd29FWURZa2FoMUdxNkpIbkxRVGIKdWdRVWEyb3J4Z09odUFaQm1PU0ExSUdrSllGOFFLWXhPMHg3TFVPSkVEcDhVVTdGQkVEd2JJcldJNGdUSzZiUwp2WklrVUpmVFh3aTZabHhaNzZRcVVSc3FkN081eW9HeTdDTUhIcDIraVcwVGduRTJuUzBWSy9RMGIwNXY5bUp1Cnp2SWZBNm9DSE1BemR0YkM5V3c1Y3p6bUhCTWdRdVhLZ3ZIdmR1eEFnd2huZ3hqc3Z1NC82aVI4dVp3bVFmby8KU0NvOUxvTHF0dGhzZ1Q3U1Eyam5aTFB0WmVEaTZiOGMyOVcwbzRReXk5Y24ySEtIVVNSVU9lcmpCWXYrTlBWbwpNeXRQSFNCV0VKOCtPNC81a3cvV1Y5bDE1V0dTNll1ODMrTm9iL2p0QW9JQkFRQ3QxSTZLbWlIMHN1RStEbitLCjJWaEVmd0FHUVU1S1YwU1JMZEhJaTI3Mjc0RSsxOS8zQUMvYjRpM0E5STNtZnF3d3NNWWIxK0NVc1ErVS9TY0YKSk9XZFpsSXgzOVJuUUplb0V0NGJ5OXQzMUdpOTMwNXR6MHpwcXhmNVI2Q2xTdG9wWXNkSllEQ3E0cmt3NjREYgplaWRVMm85bUxNTy9Xb3JNaFdwdlJnTncyd2VhQ2Z3MUErMFpiaS8zS3BkSDl2Y3FQN3NmNzJoNldYV000dlppCktIWjVXclhVdCsxNjU0UTZIanh3TUYvc2ZkMDh4ajhic2R2WEVyeVlxVWRNOGRJVENicDQvdWFWSFZpRXlXZ0UKTHBST3l3ZjNIbjQrSUFYdTJXTFBtWTlxSWd0NmpTdzkyYnkvU1RyTnZDNUhDblJvOU54ajhSSWFjT21aTnFWZApsUy9CQW9JQkFRQzRaWEdlT0dvckxHSzBBcG9HNDlzOVFQRS9IbkIyK1JkcUZFa2Ywd0RoUDZxZURTUnZiRzFqCkQreGdlNHpicXp2Z3RIdThYZWtGRm9EWXpPemx6RGh1WkZFUTkvQnhFV1ZlVlRqcnRjdDJtRU85bnZVclN5V1UKemplaThoVDlzaktxSENPb0R1LzJvMDJuYStFZFNTY21UbUxienJTNkM2cVZhazIrbDBEMWx6NW5YNWFHWVdqTAppazZkNisyeDE0VHZrc1pieTZmQjJPL1ZiSHZ5d2w2ZDZ3eWhvcTVZQmhxQ0tCQzJnU3R5aVVSQkNEU1gvOU93CmtmMk05UnUwTlNYREhkMW9ReXBmbGJaWVlBVjF4MGN4R3lyQTdqV01UQzlNdTZVN1FzRXd6eVV3eHc3d3VMSnQKZ3BIcEd6MktiUkg4MFdNVmN0UG5TaTRHeEE0MGI3aU8KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=

persistence:
  enabled: true
  postfix: dbpvc
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""
