apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mandan-site.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.tls.crt }}
  tls.key: {{ .Values.secrets.tls.key }}
