apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mandan-site.fullname" . }}-mongodb-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mandan-site.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-root-username: {{ .Values.secrets.mongodb.username }}
  mongodb-root-password: {{ .Values.secrets.mongodb.password }}
