apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mandan-site.fullname" . }}-mongoexp-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mandan-site.labels" . | nindent 4 }}
type: Opaque
data:
  mongo-express-username: {{ .Values.secrets.mongoexp.username }}
  mongo-express-password: {{ .Values.secrets.mongoexp.password }}
