apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mandan-site.fullname" . }}-mongo-cfm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mandan-site.labels" . | nindent 4 }}
data:
  mongodb_url: {{ include "mandan-site.fullname" . }}-mongodb-svc
