apiVersion: v1
kind: Service
metadata:
  name: {{ include "mandan-site.fullname" . }}-mongodb-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mandan-site.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
  - port: {{ .Values.mongodb.service.port }}
    targetPort: {{ .Values.mongodb.service.port }}
    protocol: TCP
    name: mongodb-svc-port
  selector:
    app: {{ include "mandan-site.fullname" . }}-mongodb
